### PR TITLE
README.md: Remove unnecessary header

### PR DESCRIPTION
**Pull request by cgwalters**
I'm really just testing PRs+homu.

### CODE REVIEW

**Comment by cgwalters** [comment]
Homu should be set up now, try it?

**Comment by baude** [comment]
@rh-atomic-bot r+ 37c49ac

**Comment by jlebon** [comment]
The tester right now is only testing master, so the YAML needs:

```yaml
branches:
  - master
  - auto
  - try
```

**Comment by cgwalters** [comment]
@rh-atomic-bot r-

**Comment by cgwalters** [comment]
@rh-atomic-bot force

**Comment by cgwalters** [comment]
Cancellation should work but doesn't seem to, hmm.

**Comment by cgwalters** [comment]
@rh-atomic-bot retry

**Comment by baude** [comment]
@rh-atomic-bot r+ 37c49a

**Pull request closed without merging**
