### PR TITLE
Bug Fixups:

### PR DESCRIPTION
**Pull request by baude**
1. Fix compilation errors related to the RHEL toolchain.
2. Add error handling for when the output file cannot be written due to permissions.
3. Fix bug for free of output when no YAML data is parsed.

### CODE REVIEW

**Comment by baude** [comment]
@cgwalters would you mind peeking at this PR; specifically at the handling of the CFLAGs.  I couldn't get it work like ostree so I added them more manually.

**Comment by cgwalters** [comment]
Yep, seems sane.

@rh-atomic-bot r+ 634aaba

**Comment by cgwalters** [comment]
Although on second thought, the reason we use the `CC_CHECK_FLAGS_APPEND` thing is to avoid erroring out if the compiler doesn't understand a flag.  And you're very likely to hit e.g. the RHEL7 gcc not understanding `-Werror=misleading-indentation` etc.

If you remind me next week I can quickly do the autogoo to wire this up in the same way.

**Comment by baude** [comment]
@cgwalters Great.  If you provide something, I'll use it. Thanks a bunch.

**Pull request closed without merging**
