### PR TITLE
Make internal functions static, fix prototype for (void) funcs

### PR DESCRIPTION
**Pull request by cgwalters**
In C, `()` means `(int)` by default, change the functions to use
`(void)`.

Also, all of these functions and data members should be static,
since they're internal only.

Copy the `attributes.m4` that came from systemd (which came from
some Gentoo project) and use it to detect the compiler-supported
warnings.

### CODE REVIEW

**Comment by baude** [comment]
@rh-atomic-bot bot, retest this please

**Comment by baude** [comment]
@rh-atomic-bot bot, retest this please.

**Comment by jlebon** [comment]
bot, retest this please

**Comment by baude** [comment]
lgtm ... merging

**Comment by baude** [comment]
@rh-atomic-bot r+ 99ddd72

**Pull request merged**
